/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeusw_epeios_FlowInputStream */

#ifndef _Included_org_zeusw_epeios_FlowInputStream
#define _Included_org_zeusw_epeios_FlowInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef org_zeusw_epeios_FlowInputStream_MAX_SKIP_BUFFER_SIZE
#define org_zeusw_epeios_FlowInputStream_MAX_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     org_zeusw_epeios_FlowInputStream
 * Method:    constructor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeusw_epeios_FlowInputStream_constructor
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_zeusw_epeios_FlowInputStream
 * Method:    destructor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeusw_epeios_FlowInputStream_destructor
  (JNIEnv *, jobject);

/*
 * Class:     org_zeusw_epeios_FlowInputStream
 * Method:    available
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zeusw_epeios_FlowInputStream_available
  (JNIEnv *, jobject);

/*
 * Class:     org_zeusw_epeios_FlowInputStream
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zeusw_epeios_FlowInputStream_read__
  (JNIEnv *, jobject);

/*
 * Class:     org_zeusw_epeios_FlowInputStream
 * Method:    read
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_zeusw_epeios_FlowInputStream_read___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_zeusw_epeios_FlowInputStream
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_zeusw_epeios_FlowInputStream_read___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
