/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class XMLPreprocessorDemo */

#ifndef _Included_XMLPreprocessorDemo
#define _Included_XMLPreprocessorDemo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
