/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcmc */

#ifndef _Included_jcmc
#define _Included_jcmc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jcmc
 * Method:    bug
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jcmc_bug
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
