/* $Id$ */

#include "nsISupports.idl"
#include "nsIDOMDocument.idl"

// Private object (using 'createInstance()'.
[scriptable, uuid(f1e695a0-b2f1-4a30-ac62-48a9edd9558a)]
interface iegeckocom
: nsISupports
{
	void RegisteringStart();
	void Register(
		in nsIDOMwindow Window,
		in string UIDesignation );	
	void RegisteringEnd();
	void Unregister();
};