/* $Id$ */

#include "nsISupports.idl"

// Shared object, (using 'getService()').
[scriptable, uuid(82aff662-258f-4644-a1bb-c0e22f55595d)]
interface ieshared
: nsISupports
{
	void Test();
	void Set( in string Value );
	string Get();



};


// Private object (using 'createInstance()'.
[scriptable, uuid(eb11441c-aedc-48a2-ba79-936372a30382)]
  interface ieprivate : nsISupports
  {

  };
