/*
	'iemobda.xpt' by Claude SIMON (http://zeusw.org/).

	 This file is part of 'emobda' software.

    'emobda' is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    'emobda' is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with 'emobda'.  If not, see <http://www.gnu.org/licenses/>.
*/

// $Id$

#include "nsIDOMWindow.idl"

// Private object (using 'createInstance()'.
[scriptable, uuid(cfee5019-09e1-4d5c-af89-0ffadf903df5)]
interface iemobdacom
: nsISupports
{
	void RegisteringStart();
	void Register( in nsIDOMwindow Window );	
	void RegisterAlone( in nsIDOMwindow Window );	
	void RegisteringEnd( in string ConfigFile );
	void Retire();
};