# $Id$

all:
	make -C _root -I .. -f Makefile
	make -C documentation -I .. -f Makefile
	make -C software -I .. -f Makefile
	make -C download -I .. -f Makefile
	make -C cvs_ -I .. -f Makefile
	make -C libraries -I .. -f Makefile
