# $Id$

all:
	make -C _root -I .. -f Makefile
	make -C about -I .. -f Makefile
	make -C general -I .. -f Makefile
	make -C software -I .. -f Makefile
	make -C libraries -I .. -f Makefile
	make -C etmc -I .. -f Makefile
	make -C ecgi -I .. -f Makefile
	make -C ebkd -I .. -f Makefile
	make -C epeios -I .. -f Makefile
