# $Id$

include Makefile.header

mkf = ~/cvs/epeios/workshop/web/epeios.org/Makefile.compress

filelist = 

all:
	$(copy) $(doc)/personnal/cv.pdf $(dest)
	$(copy) $(doc)/personnal/cv.doc $(dest)
	$(copy) data/mll2html/mailinglists.txt data/mll2html/mailinglists.html $(dest)/mll2html
	$(copy) $(cvs)/epeios/devel/CHANGELOG.txt $(dest)/epeios/CHANGELOG
	$(copy) $(cvs)/ecgi/devel/CHANGELOG.txt $(dest)/ecgi/CHANGELOG
	$(copy) $(cvs)/etmc/devel/CHANGELOG.txt $(dest)/etmc/CHANGELOG
	$(copy) $(cvs)/ebkd/devel/CHANGELOG.txt $(dest)/ebkd/CHANGELOG
	$(copy) $(cvs)/exml/devel/CHANGELOG.txt $(dest)/exml/CHANGELOG
	$(copy) $(cvs)/emth/devel/CHANGELOG.txt $(dest)/emth/CHANGELOG
#	$(copy) $(cvs)/ejava/libs/CHANGELOG.txt $(dest)/ejava/CHANGELOG
	$(copy) $(cvs)/epeios/tools/reveal/CHANGELOG.txt $(dest)/reveal/CHANGELOG
	$(copy) $(cvs)/epeios/tools/mll2html/CHANGELOG.txt $(dest)/mll2html/CHANGELOG
	$(copy) $(cvs)/etmc/apps/backend/CHANGELOG.txt $(dest)/tmcde/backend/CHANGELOG
	$(copy) $(cvs)/etmc/apps/cgid/CHANGELOG.txt $(dest)/tmcde/CGID/CHANGELOG
	$(copy) $(cvs)/ebkd/apps/getbkdapi/CHANGELOG.txt $(dest)/getbkdapi/CHANGELOG
	$(copy) $(cvs)/etmc/apps/backend/API.xml $(dest)/getbkdapi
	$(copy) $(cvs)/ebkd/stable/*.xsl $(dest)/getbkdapi
	$(copy) $(cvs)/etmc/apps/cgid/tmcde.h $(dest)/getbkdapi
ifeq ("$(EPEIOS_ENV)","gnu")
	make -C $(dest)/epeios/quickdoc -f $(mkf)
	make -C $(dest)/etmc/quickdoc -f $(mkf)
	make -C $(dest)/ecgi/quickdoc -f $(mkf) 
	make -C $(dest)/ebkd/quickdoc -f $(mkf)
	make -C $(dest)/exml/quickdoc -f $(mkf)
	make -C $(dest)/emth/quickdoc -f $(mkf)
endif

