# $Id$

ifeq ("$(EPEIOS_OS)","windows")
templates = t:
rootdir=/cvs/epeios
dest = /website
copy = cp
move = move
mkdir = c:\tools\mkdir
endif

ifeq ("$(EPEIOS_OS)","linux")
rootdir=/home/csimon/libs/epeios
templates = $(rootdir)/workshop/web/templates
dest = /home/csimon/website
copy = cp
move = mv
mkdir = mkdir
endif

crpfile = $(templates)/$(EPEIOS_OS).crp
rootxsl = $(templates)/epeios.org/page.xsl
doc = $(rootdir)/documentation
xsl = $(templates)/*.xsl